<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xiaoye</groupId>
        <artifactId>xiaoye-boot-starter-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>xiaoye-starter-data</artifactId>
    <packaging>jar</packaging>
    <name>XiaoYe Starter Data</name>
    <description>数据持久化模块：MyBatis Plus、分页、自动填充</description>

    <dependencies>
        <dependency>
            <groupId>com.xiaoye</groupId>
            <artifactId>xiaoye-starter-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.3.1</version>
        </dependency>
    </dependencies>
</project>
